### ISSUE TITLE
Add Mathjax for tex formulas

### ISSUE THREAD

**Issue by retuxx** [nsteiner/kdoc#11]
I'm working on a documentation website that uses plenty of tex formulas. While looking for a kirby theme I saw your project which looks quite nice. Do you think it is possible to add Mathjax in order to render high quality tex formulas out of the box?

**Comment by nsteiner** [comment]
@retuxx I was able to confirm that Mathjax works nicely with KDoc, and it's easy to implement. Here's one way to do it that I just tested (see screenshot of results below).

To install, I pasted a simple example from the [MathJax getting started page](http://docs.mathjax.org/en/latest/start.html) into the header include of KDoc. This is just put anywhere inside the ```<head>``` tag. When you download KDoc, you can find the header include in ```/site/snippets/header.php```

```
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}});
</script>
<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_CHTML">
</script>
```

Once that's in place, you can just start using tex formulas anywhere in the content of the site you're building and they will render as expected when you view or preview the page.

<img width="972" alt="screen shot 2016-12-30 at 3 13 11 pm" src="https://cloud.githubusercontent.com/assets/111835/21571990/89bba548-cea2-11e6-8c97-7c44195e0d0c.png">

I hope that's everything you're looking for, but don't hesitate to write if i'm misunderstanding anything - I'm not experienced in using Mathjax or tex formulas.

cheers

**Comment by retuxx** [comment]
Thank you @nsteiner for your tutorial. The integration looks straightforward. Do you think MathJax is worth adding it to the kdoc theme in order to provide tex formulas out of the box?

**Comment by nsteiner** [comment]
You're welcome @retuxx. I'm hesitant to add external libraries, but I do think it's worth adding. It would be especially good if there's a simple checkbox "turn on MathJax" setting that will prevent it from being downloaded on KDoc sites that don't need it. So I'll re-open this ticket and give that a shot.

**Comment by retuxx** [comment]
I'm new to kirby so I don't know much about its mechanics but isn't this what templates are used for? If i get things right, you should be able to add another template that is exactly like `default` except of adding MathJax. Correct me if I'm wrong.

**Comment by nsteiner** [comment]
@retuxx typically templates in Kirby are for enabling the creation of pages that include a unique structure of input fields (e.g. project pages that have description and author input fields not found in other templates). 

It is (arguably) better to keep the option site-wide since there's not a lot of benefit from just enabling it on a page-by-page basis (once it's loaded, it'll be cached). I'm also unsure if adding a MathJax template option will be confusing for people who don't know what MathJax or tex formulas are.   

That said, adding a checkbox (as I had suggested) is also weird in that once it's checked and formulas are used somewhere in the site, you wouldn't want it to ever ben un-checked.

So I'm still considering how best to implement. If you have more opinions/thoughts on this, they would be welcome.

**Comment by retuxx** [comment]
How about using kirby's config engine at first? It allows us to set a configuration value such as 'kdoc.mathjax'. We can set this value to 'false' by default not hindering other uses who don't care about mathjax.

**Comment by nsteiner** [comment]
@retuxx that's perfect, I'll proceed with that option.

**Comment by nsteiner** [comment]
This is now merged into `master` branch, thanks so much @retuxx for the contribution.
