### ISSUE TITLE
Remove warnings regarding 'role'

### ISSUE THREAD

**Issue by retuxx** [nsteiner/kdoc#16]
When checking the example page with the [w3c validator](https://validator.w3.org/) one can see that it reports warnings regarding the roles "banner", "navigation", and "contentinfo". Are they really necessary? I think this theme should be w3c compliant. By the way, the issue regarding the enclosing div element has been merged already. The issue regarding the nested p element has been removed in https://github.com/nsteiner/kdoc/pull/15.

**Comment by nsteiner** [comment]
@retuxx thanks. This was a leftover from DOCter (which inspired KDoc).  I was skeptical about this at first because DOCter was written by folks who understand coding for accessibility, but after reading a bit more about this particular issue, it seems that non-critical role definitions are discouraged. I've got them removed in a forthcoming commit.
